//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbPedidosEncargosEntities : DbContext
    {
        public dbPedidosEncargosEntities()
            : base("name=dbPedidosEncargosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbArticulos> tbArticulos { get; set; }
        public virtual DbSet<tbCargos> tbCargos { get; set; }
        public virtual DbSet<tbCategoria> tbCategoria { get; set; }
        public virtual DbSet<tbClientes> tbClientes { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbDirecciones> tbDirecciones { get; set; }
        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }
        public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }
        public virtual DbSet<tbFabricas> tbFabricas { get; set; }
        public virtual DbSet<tbMetodoPago> tbMetodoPago { get; set; }
        public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }
        public virtual DbSet<tbPantallas> tbPantallas { get; set; }
        public virtual DbSet<tbPedidos> tbPedidos { get; set; }
        public virtual DbSet<tbPedidosDetalles> tbPedidosDetalles { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbRolesXPantalla> tbRolesXPantalla { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<VW_ClientesIndex> VW_ClientesIndex { get; set; }
        public virtual DbSet<VW_DireccionesIndex> VW_DireccionesIndex { get; set; }
        public virtual DbSet<VW_UsuariosIndex> VW_UsuariosIndex { get; set; }
    
        public virtual int UDP_BorrarUsuario(Nullable<int> idEdicion)
        {
            var idEdicionParameter = idEdicion.HasValue ?
                new ObjectParameter("IdEdicion", idEdicion) :
                new ObjectParameter("IdEdicion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_BorrarUsuario", idEdicionParameter);
        }
    
        public virtual int UDP_EdicionUsuario(Nullable<int> usu_Id, Nullable<int> emp_Id, Nullable<int> rol_id, Nullable<int> usuarioModificacion)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var rol_idParameter = rol_id.HasValue ?
                new ObjectParameter("rol_id", rol_id) :
                new ObjectParameter("rol_id", typeof(int));
    
            var usuarioModificacionParameter = usuarioModificacion.HasValue ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_EdicionUsuario", usu_IdParameter, emp_IdParameter, rol_idParameter, usuarioModificacionParameter);
        }
    
        public virtual int UDP_InsertarUsuario(string usu_Usuario, string usu_Contrasenia, Nullable<int> emp_Id, Nullable<int> rol_id, Nullable<int> usu_UsuarioCreacion)
        {
            var usu_UsuarioParameter = usu_Usuario != null ?
                new ObjectParameter("usu_Usuario", usu_Usuario) :
                new ObjectParameter("usu_Usuario", typeof(string));
    
            var usu_ContraseniaParameter = usu_Contrasenia != null ?
                new ObjectParameter("usu_Contrasenia", usu_Contrasenia) :
                new ObjectParameter("usu_Contrasenia", typeof(string));
    
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var rol_idParameter = rol_id.HasValue ?
                new ObjectParameter("rol_id", rol_id) :
                new ObjectParameter("rol_id", typeof(int));
    
            var usu_UsuarioCreacionParameter = usu_UsuarioCreacion.HasValue ?
                new ObjectParameter("usu_UsuarioCreacion", usu_UsuarioCreacion) :
                new ObjectParameter("usu_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_InsertarUsuario", usu_UsuarioParameter, usu_ContraseniaParameter, emp_IdParameter, rol_idParameter, usu_UsuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_Login_Result> UDP_Login(string usu_Usuario, string usu_Contrasenia)
        {
            var usu_UsuarioParameter = usu_Usuario != null ?
                new ObjectParameter("usu_Usuario", usu_Usuario) :
                new ObjectParameter("usu_Usuario", typeof(string));
    
            var usu_ContraseniaParameter = usu_Contrasenia != null ?
                new ObjectParameter("usu_Contrasenia", usu_Contrasenia) :
                new ObjectParameter("usu_Contrasenia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Login_Result>("UDP_Login", usu_UsuarioParameter, usu_ContraseniaParameter);
        }
    
        public virtual int UDP_PedidoDetalle_Delete(Nullable<int> pede_Id, Nullable<int> pede_UsuarioModificacion)
        {
            var pede_IdParameter = pede_Id.HasValue ?
                new ObjectParameter("pede_Id", pede_Id) :
                new ObjectParameter("pede_Id", typeof(int));
    
            var pede_UsuarioModificacionParameter = pede_UsuarioModificacion.HasValue ?
                new ObjectParameter("pede_UsuarioModificacion", pede_UsuarioModificacion) :
                new ObjectParameter("pede_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_PedidoDetalle_Delete", pede_IdParameter, pede_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_PedidoDetalle_Insert(Nullable<int> ped_Id, Nullable<int> art_Id, Nullable<int> pede_cantidad, Nullable<int> pede_UsuarioCreacion)
        {
            var ped_IdParameter = ped_Id.HasValue ?
                new ObjectParameter("ped_Id", ped_Id) :
                new ObjectParameter("ped_Id", typeof(int));
    
            var art_IdParameter = art_Id.HasValue ?
                new ObjectParameter("art_Id", art_Id) :
                new ObjectParameter("art_Id", typeof(int));
    
            var pede_cantidadParameter = pede_cantidad.HasValue ?
                new ObjectParameter("pede_cantidad", pede_cantidad) :
                new ObjectParameter("pede_cantidad", typeof(int));
    
            var pede_UsuarioCreacionParameter = pede_UsuarioCreacion.HasValue ?
                new ObjectParameter("pede_UsuarioCreacion", pede_UsuarioCreacion) :
                new ObjectParameter("pede_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_PedidoDetalle_Insert", ped_IdParameter, art_IdParameter, pede_cantidadParameter, pede_UsuarioCreacionParameter);
        }
    
        public virtual int UDP_tbArticulo_Update(Nullable<int> art_Id, string art_Nombre, Nullable<decimal> art_Precio, Nullable<int> cat_Id, Nullable<int> art_Stock, Nullable<int> art_Fabrica, Nullable<int> art_UsuarioCreacion)
        {
            var art_IdParameter = art_Id.HasValue ?
                new ObjectParameter("art_Id", art_Id) :
                new ObjectParameter("art_Id", typeof(int));
    
            var art_NombreParameter = art_Nombre != null ?
                new ObjectParameter("art_Nombre", art_Nombre) :
                new ObjectParameter("art_Nombre", typeof(string));
    
            var art_PrecioParameter = art_Precio.HasValue ?
                new ObjectParameter("art_Precio", art_Precio) :
                new ObjectParameter("art_Precio", typeof(decimal));
    
            var cat_IdParameter = cat_Id.HasValue ?
                new ObjectParameter("cat_Id", cat_Id) :
                new ObjectParameter("cat_Id", typeof(int));
    
            var art_StockParameter = art_Stock.HasValue ?
                new ObjectParameter("art_Stock", art_Stock) :
                new ObjectParameter("art_Stock", typeof(int));
    
            var art_FabricaParameter = art_Fabrica.HasValue ?
                new ObjectParameter("art_Fabrica", art_Fabrica) :
                new ObjectParameter("art_Fabrica", typeof(int));
    
            var art_UsuarioCreacionParameter = art_UsuarioCreacion.HasValue ?
                new ObjectParameter("art_UsuarioCreacion", art_UsuarioCreacion) :
                new ObjectParameter("art_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbArticulo_Update", art_IdParameter, art_NombreParameter, art_PrecioParameter, cat_IdParameter, art_StockParameter, art_FabricaParameter, art_UsuarioCreacionParameter);
        }
    
        public virtual int UDP_tbArticulos_Delete(Nullable<int> art_Id, Nullable<int> art_UsuarioModificacion)
        {
            var art_IdParameter = art_Id.HasValue ?
                new ObjectParameter("art_Id", art_Id) :
                new ObjectParameter("art_Id", typeof(int));
    
            var art_UsuarioModificacionParameter = art_UsuarioModificacion.HasValue ?
                new ObjectParameter("art_UsuarioModificacion", art_UsuarioModificacion) :
                new ObjectParameter("art_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbArticulos_Delete", art_IdParameter, art_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbArticulos_Insert(string art_Nombre, Nullable<decimal> art_Precio, Nullable<int> cat_Id, Nullable<int> art_Stock, Nullable<int> art_Fabrica, Nullable<int> art_UsuarioCreacion)
        {
            var art_NombreParameter = art_Nombre != null ?
                new ObjectParameter("art_Nombre", art_Nombre) :
                new ObjectParameter("art_Nombre", typeof(string));
    
            var art_PrecioParameter = art_Precio.HasValue ?
                new ObjectParameter("art_Precio", art_Precio) :
                new ObjectParameter("art_Precio", typeof(decimal));
    
            var cat_IdParameter = cat_Id.HasValue ?
                new ObjectParameter("cat_Id", cat_Id) :
                new ObjectParameter("cat_Id", typeof(int));
    
            var art_StockParameter = art_Stock.HasValue ?
                new ObjectParameter("art_Stock", art_Stock) :
                new ObjectParameter("art_Stock", typeof(int));
    
            var art_FabricaParameter = art_Fabrica.HasValue ?
                new ObjectParameter("art_Fabrica", art_Fabrica) :
                new ObjectParameter("art_Fabrica", typeof(int));
    
            var art_UsuarioCreacionParameter = art_UsuarioCreacion.HasValue ?
                new ObjectParameter("art_UsuarioCreacion", art_UsuarioCreacion) :
                new ObjectParameter("art_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbArticulos_Insert", art_NombreParameter, art_PrecioParameter, cat_IdParameter, art_StockParameter, art_FabricaParameter, art_UsuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_tbArticulos_Select_Result> UDP_tbArticulos_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbArticulos_Select_Result>("UDP_tbArticulos_Select");
        }
    
        public virtual int UDP_tbCargo_Delete(Nullable<int> car_Id)
        {
            var car_IdParameter = car_Id.HasValue ?
                new ObjectParameter("car_Id", car_Id) :
                new ObjectParameter("car_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbCargo_Delete", car_IdParameter);
        }
    
        public virtual int UDP_tbCargo_Update(Nullable<int> car_Id, string car_Nombre, Nullable<int> car_UsuarioModificacion)
        {
            var car_IdParameter = car_Id.HasValue ?
                new ObjectParameter("car_Id", car_Id) :
                new ObjectParameter("car_Id", typeof(int));
    
            var car_NombreParameter = car_Nombre != null ?
                new ObjectParameter("car_Nombre", car_Nombre) :
                new ObjectParameter("car_Nombre", typeof(string));
    
            var car_UsuarioModificacionParameter = car_UsuarioModificacion.HasValue ?
                new ObjectParameter("car_UsuarioModificacion", car_UsuarioModificacion) :
                new ObjectParameter("car_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbCargo_Update", car_IdParameter, car_NombreParameter, car_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbCargos_Insert(string car_Nombre, Nullable<int> car_UsuarioCreacion)
        {
            var car_NombreParameter = car_Nombre != null ?
                new ObjectParameter("car_Nombre", car_Nombre) :
                new ObjectParameter("car_Nombre", typeof(string));
    
            var car_UsuarioCreacionParameter = car_UsuarioCreacion.HasValue ?
                new ObjectParameter("car_UsuarioCreacion", car_UsuarioCreacion) :
                new ObjectParameter("car_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbCargos_Insert", car_NombreParameter, car_UsuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_tbCargos_Select_Result> UDP_tbCargos_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbCargos_Select_Result>("UDP_tbCargos_Select");
        }
    
        public virtual int UDP_tbCategorias_Delete(Nullable<int> cat_Id)
        {
            var cat_IdParameter = cat_Id.HasValue ?
                new ObjectParameter("cat_Id", cat_Id) :
                new ObjectParameter("cat_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbCategorias_Delete", cat_IdParameter);
        }
    
        public virtual int UDP_tbCategorias_Insert(string cat_Descripcion, Nullable<int> cat_UsuarioCreacion)
        {
            var cat_DescripcionParameter = cat_Descripcion != null ?
                new ObjectParameter("cat_Descripcion", cat_Descripcion) :
                new ObjectParameter("cat_Descripcion", typeof(string));
    
            var cat_UsuarioCreacionParameter = cat_UsuarioCreacion.HasValue ?
                new ObjectParameter("cat_UsuarioCreacion", cat_UsuarioCreacion) :
                new ObjectParameter("cat_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbCategorias_Insert", cat_DescripcionParameter, cat_UsuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_tbCategorias_Select_Result> UDP_tbCategorias_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbCategorias_Select_Result>("UDP_tbCategorias_Select");
        }
    
        public virtual int UDP_tbCategorias_Update(Nullable<int> cat_Id, string cat_Descripcion, Nullable<int> cat_UsuarioModificacion)
        {
            var cat_IdParameter = cat_Id.HasValue ?
                new ObjectParameter("cat_Id", cat_Id) :
                new ObjectParameter("cat_Id", typeof(int));
    
            var cat_DescripcionParameter = cat_Descripcion != null ?
                new ObjectParameter("cat_Descripcion", cat_Descripcion) :
                new ObjectParameter("cat_Descripcion", typeof(string));
    
            var cat_UsuarioModificacionParameter = cat_UsuarioModificacion.HasValue ?
                new ObjectParameter("cat_UsuarioModificacion", cat_UsuarioModificacion) :
                new ObjectParameter("cat_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbCategorias_Update", cat_IdParameter, cat_DescripcionParameter, cat_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbClientes_Delete(Nullable<int> cli_Id, Nullable<int> cli_UsuarioModificacion)
        {
            var cli_IdParameter = cli_Id.HasValue ?
                new ObjectParameter("cli_Id", cli_Id) :
                new ObjectParameter("cli_Id", typeof(int));
    
            var cli_UsuarioModificacionParameter = cli_UsuarioModificacion.HasValue ?
                new ObjectParameter("cli_UsuarioModificacion", cli_UsuarioModificacion) :
                new ObjectParameter("cli_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbClientes_Delete", cli_IdParameter, cli_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbClientes_Insert(string cli_Nombre, string cli_Apellido, string cli_Telefono, string cli_CorreoElectronico, Nullable<decimal> cli_saldo, Nullable<decimal> cli_LimiteCredito, Nullable<decimal> cli_Descuento, Nullable<int> cli_UsuarioCreacion)
        {
            var cli_NombreParameter = cli_Nombre != null ?
                new ObjectParameter("cli_Nombre", cli_Nombre) :
                new ObjectParameter("cli_Nombre", typeof(string));
    
            var cli_ApellidoParameter = cli_Apellido != null ?
                new ObjectParameter("cli_Apellido", cli_Apellido) :
                new ObjectParameter("cli_Apellido", typeof(string));
    
            var cli_TelefonoParameter = cli_Telefono != null ?
                new ObjectParameter("cli_Telefono", cli_Telefono) :
                new ObjectParameter("cli_Telefono", typeof(string));
    
            var cli_CorreoElectronicoParameter = cli_CorreoElectronico != null ?
                new ObjectParameter("cli_CorreoElectronico", cli_CorreoElectronico) :
                new ObjectParameter("cli_CorreoElectronico", typeof(string));
    
            var cli_saldoParameter = cli_saldo.HasValue ?
                new ObjectParameter("cli_saldo", cli_saldo) :
                new ObjectParameter("cli_saldo", typeof(decimal));
    
            var cli_LimiteCreditoParameter = cli_LimiteCredito.HasValue ?
                new ObjectParameter("cli_LimiteCredito", cli_LimiteCredito) :
                new ObjectParameter("cli_LimiteCredito", typeof(decimal));
    
            var cli_DescuentoParameter = cli_Descuento.HasValue ?
                new ObjectParameter("cli_Descuento", cli_Descuento) :
                new ObjectParameter("cli_Descuento", typeof(decimal));
    
            var cli_UsuarioCreacionParameter = cli_UsuarioCreacion.HasValue ?
                new ObjectParameter("cli_UsuarioCreacion", cli_UsuarioCreacion) :
                new ObjectParameter("cli_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbClientes_Insert", cli_NombreParameter, cli_ApellidoParameter, cli_TelefonoParameter, cli_CorreoElectronicoParameter, cli_saldoParameter, cli_LimiteCreditoParameter, cli_DescuentoParameter, cli_UsuarioCreacionParameter);
        }
    
        public virtual int UDP_tbClientes_Update(Nullable<int> cli_Id, string cli_Nombre, string cli_Apellido, string cli_Telefono, string cli_CorreoElectronico, Nullable<decimal> cli_saldo, Nullable<decimal> cli_LimiteCredito, Nullable<decimal> cli_Descuento, Nullable<int> cli_UsuarioModificacion)
        {
            var cli_IdParameter = cli_Id.HasValue ?
                new ObjectParameter("cli_Id", cli_Id) :
                new ObjectParameter("cli_Id", typeof(int));
    
            var cli_NombreParameter = cli_Nombre != null ?
                new ObjectParameter("cli_Nombre", cli_Nombre) :
                new ObjectParameter("cli_Nombre", typeof(string));
    
            var cli_ApellidoParameter = cli_Apellido != null ?
                new ObjectParameter("cli_Apellido", cli_Apellido) :
                new ObjectParameter("cli_Apellido", typeof(string));
    
            var cli_TelefonoParameter = cli_Telefono != null ?
                new ObjectParameter("cli_Telefono", cli_Telefono) :
                new ObjectParameter("cli_Telefono", typeof(string));
    
            var cli_CorreoElectronicoParameter = cli_CorreoElectronico != null ?
                new ObjectParameter("cli_CorreoElectronico", cli_CorreoElectronico) :
                new ObjectParameter("cli_CorreoElectronico", typeof(string));
    
            var cli_saldoParameter = cli_saldo.HasValue ?
                new ObjectParameter("cli_saldo", cli_saldo) :
                new ObjectParameter("cli_saldo", typeof(decimal));
    
            var cli_LimiteCreditoParameter = cli_LimiteCredito.HasValue ?
                new ObjectParameter("cli_LimiteCredito", cli_LimiteCredito) :
                new ObjectParameter("cli_LimiteCredito", typeof(decimal));
    
            var cli_DescuentoParameter = cli_Descuento.HasValue ?
                new ObjectParameter("cli_Descuento", cli_Descuento) :
                new ObjectParameter("cli_Descuento", typeof(decimal));
    
            var cli_UsuarioModificacionParameter = cli_UsuarioModificacion.HasValue ?
                new ObjectParameter("cli_UsuarioModificacion", cli_UsuarioModificacion) :
                new ObjectParameter("cli_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbClientes_Update", cli_IdParameter, cli_NombreParameter, cli_ApellidoParameter, cli_TelefonoParameter, cli_CorreoElectronicoParameter, cli_saldoParameter, cli_LimiteCreditoParameter, cli_DescuentoParameter, cli_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbDirecciones_Delete(Nullable<int> dire_id)
        {
            var dire_idParameter = dire_id.HasValue ?
                new ObjectParameter("dire_id", dire_id) :
                new ObjectParameter("dire_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbDirecciones_Delete", dire_idParameter);
        }
    
        public virtual int UDP_tbDirecciones_Insert(string dire_Calle, string dire_Comuna, string mun_Id, Nullable<int> cli_Id, Nullable<int> dire_UsuarioCreacion)
        {
            var dire_CalleParameter = dire_Calle != null ?
                new ObjectParameter("dire_Calle", dire_Calle) :
                new ObjectParameter("dire_Calle", typeof(string));
    
            var dire_ComunaParameter = dire_Comuna != null ?
                new ObjectParameter("dire_Comuna", dire_Comuna) :
                new ObjectParameter("dire_Comuna", typeof(string));
    
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var cli_IdParameter = cli_Id.HasValue ?
                new ObjectParameter("cli_Id", cli_Id) :
                new ObjectParameter("cli_Id", typeof(int));
    
            var dire_UsuarioCreacionParameter = dire_UsuarioCreacion.HasValue ?
                new ObjectParameter("dire_UsuarioCreacion", dire_UsuarioCreacion) :
                new ObjectParameter("dire_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbDirecciones_Insert", dire_CalleParameter, dire_ComunaParameter, mun_IdParameter, cli_IdParameter, dire_UsuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_tbDirecciones_Select_Result> UDP_tbDirecciones_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbDirecciones_Select_Result>("UDP_tbDirecciones_Select");
        }
    
        public virtual int UDP_tbDirecciones_Update(Nullable<int> dire_ID, string dire_Calle, string dire_Comuna, string mun_Id, Nullable<int> cli_Id, Nullable<int> dire_UsuarioModificacion)
        {
            var dire_IDParameter = dire_ID.HasValue ?
                new ObjectParameter("dire_ID", dire_ID) :
                new ObjectParameter("dire_ID", typeof(int));
    
            var dire_CalleParameter = dire_Calle != null ?
                new ObjectParameter("dire_Calle", dire_Calle) :
                new ObjectParameter("dire_Calle", typeof(string));
    
            var dire_ComunaParameter = dire_Comuna != null ?
                new ObjectParameter("dire_Comuna", dire_Comuna) :
                new ObjectParameter("dire_Comuna", typeof(string));
    
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var cli_IdParameter = cli_Id.HasValue ?
                new ObjectParameter("cli_Id", cli_Id) :
                new ObjectParameter("cli_Id", typeof(int));
    
            var dire_UsuarioModificacionParameter = dire_UsuarioModificacion.HasValue ?
                new ObjectParameter("dire_UsuarioModificacion", dire_UsuarioModificacion) :
                new ObjectParameter("dire_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbDirecciones_Update", dire_IDParameter, dire_CalleParameter, dire_ComunaParameter, mun_IdParameter, cli_IdParameter, dire_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbEmpleados_Delete(Nullable<int> emp_Id)
        {
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbEmpleados_Delete", emp_IdParameter);
        }
    
        public virtual int UDP_tbEmpleados_Insert(string emp_Nombre, string emp_Apellido, string emp_Sexo, string mun_Id, string emp_DireccionExacta, string estciv_Id, string emp_Telefono, string emp_CorreoElectronico, string emp_FechaNacimiento, string emp_FechaContratacion, string car_Id, Nullable<int> emp_UsuarioCreacion)
        {
            var emp_NombreParameter = emp_Nombre != null ?
                new ObjectParameter("emp_Nombre", emp_Nombre) :
                new ObjectParameter("emp_Nombre", typeof(string));
    
            var emp_ApellidoParameter = emp_Apellido != null ?
                new ObjectParameter("emp_Apellido", emp_Apellido) :
                new ObjectParameter("emp_Apellido", typeof(string));
    
            var emp_SexoParameter = emp_Sexo != null ?
                new ObjectParameter("emp_Sexo", emp_Sexo) :
                new ObjectParameter("emp_Sexo", typeof(string));
    
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var emp_DireccionExactaParameter = emp_DireccionExacta != null ?
                new ObjectParameter("emp_DireccionExacta", emp_DireccionExacta) :
                new ObjectParameter("emp_DireccionExacta", typeof(string));
    
            var estciv_IdParameter = estciv_Id != null ?
                new ObjectParameter("estciv_Id", estciv_Id) :
                new ObjectParameter("estciv_Id", typeof(string));
    
            var emp_TelefonoParameter = emp_Telefono != null ?
                new ObjectParameter("emp_Telefono", emp_Telefono) :
                new ObjectParameter("emp_Telefono", typeof(string));
    
            var emp_CorreoElectronicoParameter = emp_CorreoElectronico != null ?
                new ObjectParameter("emp_CorreoElectronico", emp_CorreoElectronico) :
                new ObjectParameter("emp_CorreoElectronico", typeof(string));
    
            var emp_FechaNacimientoParameter = emp_FechaNacimiento != null ?
                new ObjectParameter("emp_FechaNacimiento", emp_FechaNacimiento) :
                new ObjectParameter("emp_FechaNacimiento", typeof(string));
    
            var emp_FechaContratacionParameter = emp_FechaContratacion != null ?
                new ObjectParameter("emp_FechaContratacion", emp_FechaContratacion) :
                new ObjectParameter("emp_FechaContratacion", typeof(string));
    
            var car_IdParameter = car_Id != null ?
                new ObjectParameter("car_Id", car_Id) :
                new ObjectParameter("car_Id", typeof(string));
    
            var emp_UsuarioCreacionParameter = emp_UsuarioCreacion.HasValue ?
                new ObjectParameter("emp_UsuarioCreacion", emp_UsuarioCreacion) :
                new ObjectParameter("emp_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbEmpleados_Insert", emp_NombreParameter, emp_ApellidoParameter, emp_SexoParameter, mun_IdParameter, emp_DireccionExactaParameter, estciv_IdParameter, emp_TelefonoParameter, emp_CorreoElectronicoParameter, emp_FechaNacimientoParameter, emp_FechaContratacionParameter, car_IdParameter, emp_UsuarioCreacionParameter);
        }
    
        public virtual ObjectResult<UDP_tbEmpleados_Select_Result> UDP_tbEmpleados_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbEmpleados_Select_Result>("UDP_tbEmpleados_Select");
        }
    
        public virtual int UDP_tbEmpleados_Update(Nullable<int> emp_Id, string emp_Nombre, string emp_Apellido, string emp_Sexo, string mun_Id, string emp_DireccionExacta, string estciv_Id, string emp_Telefono, string emp_CorreoElectronico, string emp_FechaNacimiento, string emp_FechaContratacion, string car_Id, Nullable<int> emp_UsuarioModificacion)
        {
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var emp_NombreParameter = emp_Nombre != null ?
                new ObjectParameter("emp_Nombre", emp_Nombre) :
                new ObjectParameter("emp_Nombre", typeof(string));
    
            var emp_ApellidoParameter = emp_Apellido != null ?
                new ObjectParameter("emp_Apellido", emp_Apellido) :
                new ObjectParameter("emp_Apellido", typeof(string));
    
            var emp_SexoParameter = emp_Sexo != null ?
                new ObjectParameter("emp_Sexo", emp_Sexo) :
                new ObjectParameter("emp_Sexo", typeof(string));
    
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var emp_DireccionExactaParameter = emp_DireccionExacta != null ?
                new ObjectParameter("emp_DireccionExacta", emp_DireccionExacta) :
                new ObjectParameter("emp_DireccionExacta", typeof(string));
    
            var estciv_IdParameter = estciv_Id != null ?
                new ObjectParameter("estciv_Id", estciv_Id) :
                new ObjectParameter("estciv_Id", typeof(string));
    
            var emp_TelefonoParameter = emp_Telefono != null ?
                new ObjectParameter("emp_Telefono", emp_Telefono) :
                new ObjectParameter("emp_Telefono", typeof(string));
    
            var emp_CorreoElectronicoParameter = emp_CorreoElectronico != null ?
                new ObjectParameter("emp_CorreoElectronico", emp_CorreoElectronico) :
                new ObjectParameter("emp_CorreoElectronico", typeof(string));
    
            var emp_FechaNacimientoParameter = emp_FechaNacimiento != null ?
                new ObjectParameter("emp_FechaNacimiento", emp_FechaNacimiento) :
                new ObjectParameter("emp_FechaNacimiento", typeof(string));
    
            var emp_FechaContratacionParameter = emp_FechaContratacion != null ?
                new ObjectParameter("emp_FechaContratacion", emp_FechaContratacion) :
                new ObjectParameter("emp_FechaContratacion", typeof(string));
    
            var car_IdParameter = car_Id != null ?
                new ObjectParameter("car_Id", car_Id) :
                new ObjectParameter("car_Id", typeof(string));
    
            var emp_UsuarioModificacionParameter = emp_UsuarioModificacion.HasValue ?
                new ObjectParameter("emp_UsuarioModificacion", emp_UsuarioModificacion) :
                new ObjectParameter("emp_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbEmpleados_Update", emp_IdParameter, emp_NombreParameter, emp_ApellidoParameter, emp_SexoParameter, mun_IdParameter, emp_DireccionExactaParameter, estciv_IdParameter, emp_TelefonoParameter, emp_CorreoElectronicoParameter, emp_FechaNacimientoParameter, emp_FechaContratacionParameter, car_IdParameter, emp_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbfabrica_Delete(Nullable<int> fab_Id, Nullable<int> fab_UsuarioModificacion)
        {
            var fab_IdParameter = fab_Id.HasValue ?
                new ObjectParameter("fab_Id", fab_Id) :
                new ObjectParameter("fab_Id", typeof(int));
    
            var fab_UsuarioModificacionParameter = fab_UsuarioModificacion.HasValue ?
                new ObjectParameter("fab_UsuarioModificacion", fab_UsuarioModificacion) :
                new ObjectParameter("fab_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbfabrica_Delete", fab_IdParameter, fab_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbFabrica_Insert(string fab_Nombre, string mun_Id, string fab_DireccionExacta, string fab_Telefono, Nullable<int> usuario)
        {
            var fab_NombreParameter = fab_Nombre != null ?
                new ObjectParameter("fab_Nombre", fab_Nombre) :
                new ObjectParameter("fab_Nombre", typeof(string));
    
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var fab_DireccionExactaParameter = fab_DireccionExacta != null ?
                new ObjectParameter("fab_DireccionExacta", fab_DireccionExacta) :
                new ObjectParameter("fab_DireccionExacta", typeof(string));
    
            var fab_TelefonoParameter = fab_Telefono != null ?
                new ObjectParameter("fab_Telefono", fab_Telefono) :
                new ObjectParameter("fab_Telefono", typeof(string));
    
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbFabrica_Insert", fab_NombreParameter, mun_IdParameter, fab_DireccionExactaParameter, fab_TelefonoParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<UDP_tbfabrica_Select_Result> UDP_tbfabrica_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbfabrica_Select_Result>("UDP_tbfabrica_Select");
        }
    
        public virtual int UDP_tbfabrica_Update(Nullable<int> fab_id, string fab_Nombre, string mun_Id, string fab_DireccionExacta, string fab_Telefono, Nullable<int> usuario)
        {
            var fab_idParameter = fab_id.HasValue ?
                new ObjectParameter("fab_id", fab_id) :
                new ObjectParameter("fab_id", typeof(int));
    
            var fab_NombreParameter = fab_Nombre != null ?
                new ObjectParameter("fab_Nombre", fab_Nombre) :
                new ObjectParameter("fab_Nombre", typeof(string));
    
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var fab_DireccionExactaParameter = fab_DireccionExacta != null ?
                new ObjectParameter("fab_DireccionExacta", fab_DireccionExacta) :
                new ObjectParameter("fab_DireccionExacta", typeof(string));
    
            var fab_TelefonoParameter = fab_Telefono != null ?
                new ObjectParameter("fab_Telefono", fab_Telefono) :
                new ObjectParameter("fab_Telefono", typeof(string));
    
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbfabrica_Update", fab_idParameter, fab_NombreParameter, mun_IdParameter, fab_DireccionExactaParameter, fab_TelefonoParameter, usuarioParameter);
        }
    
        public virtual int UDP_tbMetodoPago_Delete(Nullable<int> metpago_Id, Nullable<int> metpago_UsuarioModificacion)
        {
            var metpago_IdParameter = metpago_Id.HasValue ?
                new ObjectParameter("metpago_Id", metpago_Id) :
                new ObjectParameter("metpago_Id", typeof(int));
    
            var metpago_UsuarioModificacionParameter = metpago_UsuarioModificacion.HasValue ?
                new ObjectParameter("metpago_UsuarioModificacion", metpago_UsuarioModificacion) :
                new ObjectParameter("metpago_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbMetodoPago_Delete", metpago_IdParameter, metpago_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbMetodoPago_Insert(string metpago_Descripcion, Nullable<int> metpago_UsuarioCreacion)
        {
            var metpago_DescripcionParameter = metpago_Descripcion != null ?
                new ObjectParameter("metpago_Descripcion", metpago_Descripcion) :
                new ObjectParameter("metpago_Descripcion", typeof(string));
    
            var metpago_UsuarioCreacionParameter = metpago_UsuarioCreacion.HasValue ?
                new ObjectParameter("metpago_UsuarioCreacion", metpago_UsuarioCreacion) :
                new ObjectParameter("metpago_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbMetodoPago_Insert", metpago_DescripcionParameter, metpago_UsuarioCreacionParameter);
        }
    
        public virtual int UDP_tbMetodoPago_Update(Nullable<int> metpago_Id, string metpago_Descripcion, Nullable<int> metpago_UsuarioModificacion)
        {
            var metpago_IdParameter = metpago_Id.HasValue ?
                new ObjectParameter("metpago_Id", metpago_Id) :
                new ObjectParameter("metpago_Id", typeof(int));
    
            var metpago_DescripcionParameter = metpago_Descripcion != null ?
                new ObjectParameter("metpago_Descripcion", metpago_Descripcion) :
                new ObjectParameter("metpago_Descripcion", typeof(string));
    
            var metpago_UsuarioModificacionParameter = metpago_UsuarioModificacion.HasValue ?
                new ObjectParameter("metpago_UsuarioModificacion", metpago_UsuarioModificacion) :
                new ObjectParameter("metpago_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbMetodoPago_Update", metpago_IdParameter, metpago_DescripcionParameter, metpago_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbpedidos_Delete(Nullable<int> ped_Id, Nullable<int> ped_UsuarioModificacion)
        {
            var ped_IdParameter = ped_Id.HasValue ?
                new ObjectParameter("ped_Id", ped_Id) :
                new ObjectParameter("ped_Id", typeof(int));
    
            var ped_UsuarioModificacionParameter = ped_UsuarioModificacion.HasValue ?
                new ObjectParameter("ped_UsuarioModificacion", ped_UsuarioModificacion) :
                new ObjectParameter("ped_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbpedidos_Delete", ped_IdParameter, ped_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbPedidos_Insert(Nullable<int> cli_Id, Nullable<int> dire_Id, Nullable<int> emp_Id, Nullable<int> metpago_Id, Nullable<int> ped_UsuarioCreacion)
        {
            var cli_IdParameter = cli_Id.HasValue ?
                new ObjectParameter("cli_Id", cli_Id) :
                new ObjectParameter("cli_Id", typeof(int));
    
            var dire_IdParameter = dire_Id.HasValue ?
                new ObjectParameter("dire_Id", dire_Id) :
                new ObjectParameter("dire_Id", typeof(int));
    
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var metpago_IdParameter = metpago_Id.HasValue ?
                new ObjectParameter("metpago_Id", metpago_Id) :
                new ObjectParameter("metpago_Id", typeof(int));
    
            var ped_UsuarioCreacionParameter = ped_UsuarioCreacion.HasValue ?
                new ObjectParameter("ped_UsuarioCreacion", ped_UsuarioCreacion) :
                new ObjectParameter("ped_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbPedidos_Insert", cli_IdParameter, dire_IdParameter, emp_IdParameter, metpago_IdParameter, ped_UsuarioCreacionParameter);
        }
    
        public virtual int UDP_tbpedidos_Update(Nullable<int> ped_Id, Nullable<int> cli_Id, Nullable<int> dire_id, Nullable<int> emp_id, Nullable<int> metpago_Id, Nullable<int> ped_UsuarioModificacion)
        {
            var ped_IdParameter = ped_Id.HasValue ?
                new ObjectParameter("ped_Id", ped_Id) :
                new ObjectParameter("ped_Id", typeof(int));
    
            var cli_IdParameter = cli_Id.HasValue ?
                new ObjectParameter("cli_Id", cli_Id) :
                new ObjectParameter("cli_Id", typeof(int));
    
            var dire_idParameter = dire_id.HasValue ?
                new ObjectParameter("dire_id", dire_id) :
                new ObjectParameter("dire_id", typeof(int));
    
            var emp_idParameter = emp_id.HasValue ?
                new ObjectParameter("emp_id", emp_id) :
                new ObjectParameter("emp_id", typeof(int));
    
            var metpago_IdParameter = metpago_Id.HasValue ?
                new ObjectParameter("metpago_Id", metpago_Id) :
                new ObjectParameter("metpago_Id", typeof(int));
    
            var ped_UsuarioModificacionParameter = ped_UsuarioModificacion.HasValue ?
                new ObjectParameter("ped_UsuarioModificacion", ped_UsuarioModificacion) :
                new ObjectParameter("ped_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbpedidos_Update", ped_IdParameter, cli_IdParameter, dire_idParameter, emp_idParameter, metpago_IdParameter, ped_UsuarioModificacionParameter);
        }
    
        public virtual ObjectResult<UDP_CargarMunicipios_Result> UDP_CargarMunicipios(string dep_Id)
        {
            var dep_IdParameter = dep_Id != null ?
                new ObjectParameter("dep_Id", dep_Id) :
                new ObjectParameter("dep_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_CargarMunicipios_Result>("UDP_CargarMunicipios", dep_IdParameter);
        }
    
        public virtual int UDP_tbDepartamentos_Delete(string dep_Id)
        {
            var dep_IdParameter = dep_Id != null ?
                new ObjectParameter("dep_Id", dep_Id) :
                new ObjectParameter("dep_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbDepartamentos_Delete", dep_IdParameter);
        }
    
        public virtual int UDP_tbDepartamentos_Insert(string dep_Id, string dep_Nombre, Nullable<int> dep_UsuarioCreacion)
        {
            var dep_IdParameter = dep_Id != null ?
                new ObjectParameter("dep_Id", dep_Id) :
                new ObjectParameter("dep_Id", typeof(string));
    
            var dep_NombreParameter = dep_Nombre != null ?
                new ObjectParameter("dep_Nombre", dep_Nombre) :
                new ObjectParameter("dep_Nombre", typeof(string));
    
            var dep_UsuarioCreacionParameter = dep_UsuarioCreacion.HasValue ?
                new ObjectParameter("dep_UsuarioCreacion", dep_UsuarioCreacion) :
                new ObjectParameter("dep_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbDepartamentos_Insert", dep_IdParameter, dep_NombreParameter, dep_UsuarioCreacionParameter);
        }
    
        public virtual int UDP_tbDepartamentos_Update(string dep_Id, string dep_Nombre, Nullable<int> dep_UsuarioModificacion)
        {
            var dep_IdParameter = dep_Id != null ?
                new ObjectParameter("dep_Id", dep_Id) :
                new ObjectParameter("dep_Id", typeof(string));
    
            var dep_NombreParameter = dep_Nombre != null ?
                new ObjectParameter("dep_Nombre", dep_Nombre) :
                new ObjectParameter("dep_Nombre", typeof(string));
    
            var dep_UsuarioModificacionParameter = dep_UsuarioModificacion.HasValue ?
                new ObjectParameter("dep_UsuarioModificacion", dep_UsuarioModificacion) :
                new ObjectParameter("dep_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbDepartamentos_Update", dep_IdParameter, dep_NombreParameter, dep_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbMunicipiosDelete(string mun_Id)
        {
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbMunicipiosDelete", mun_IdParameter);
        }
    
        public virtual int UDP_tbMunicipiosInsert(string dep_Id, string mun_Id, string mun_Nombre, Nullable<int> mun_UsuarioCreacion)
        {
            var dep_IdParameter = dep_Id != null ?
                new ObjectParameter("dep_Id", dep_Id) :
                new ObjectParameter("dep_Id", typeof(string));
    
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var mun_NombreParameter = mun_Nombre != null ?
                new ObjectParameter("mun_Nombre", mun_Nombre) :
                new ObjectParameter("mun_Nombre", typeof(string));
    
            var mun_UsuarioCreacionParameter = mun_UsuarioCreacion.HasValue ?
                new ObjectParameter("mun_UsuarioCreacion", mun_UsuarioCreacion) :
                new ObjectParameter("mun_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbMunicipiosInsert", dep_IdParameter, mun_IdParameter, mun_NombreParameter, mun_UsuarioCreacionParameter);
        }
    
        public virtual int UDP_tbMunicipiosUpdate(string mun_Id, string dep_Id, string mun_Nombre, Nullable<int> mun_UsuarioModificacion)
        {
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var dep_IdParameter = dep_Id != null ?
                new ObjectParameter("dep_Id", dep_Id) :
                new ObjectParameter("dep_Id", typeof(string));
    
            var mun_NombreParameter = mun_Nombre != null ?
                new ObjectParameter("mun_Nombre", mun_Nombre) :
                new ObjectParameter("mun_Nombre", typeof(string));
    
            var mun_UsuarioModificacionParameter = mun_UsuarioModificacion.HasValue ?
                new ObjectParameter("mun_UsuarioModificacion", mun_UsuarioModificacion) :
                new ObjectParameter("mun_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbMunicipiosUpdate", mun_IdParameter, dep_IdParameter, mun_NombreParameter, mun_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_CambiarPassword(string usu_Usuario, string usu_Contrasenia)
        {
            var usu_UsuarioParameter = usu_Usuario != null ?
                new ObjectParameter("usu_Usuario", usu_Usuario) :
                new ObjectParameter("usu_Usuario", typeof(string));
    
            var usu_ContraseniaParameter = usu_Contrasenia != null ?
                new ObjectParameter("usu_Contrasenia", usu_Contrasenia) :
                new ObjectParameter("usu_Contrasenia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_CambiarPassword", usu_UsuarioParameter, usu_ContraseniaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> UDP_tbArticulos_Return(string art_id)
        {
            var art_idParameter = art_id != null ?
                new ObjectParameter("art_id", art_id) :
                new ObjectParameter("art_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("UDP_tbArticulos_Return", art_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_DireccionBorrada(Nullable<int> dire_ID)
        {
            var dire_IDParameter = dire_ID.HasValue ?
                new ObjectParameter("dire_ID", dire_ID) :
                new ObjectParameter("dire_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_DireccionBorrada", dire_IDParameter);
        }
    
        public virtual int UDP_RecuperarContrasenia(string usu_Usuario, string usu_Contrasenia)
        {
            var usu_UsuarioParameter = usu_Usuario != null ?
                new ObjectParameter("usu_Usuario", usu_Usuario) :
                new ObjectParameter("usu_Usuario", typeof(string));
    
            var usu_ContraseniaParameter = usu_Contrasenia != null ?
                new ObjectParameter("usu_Contrasenia", usu_Contrasenia) :
                new ObjectParameter("usu_Contrasenia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_RecuperarContrasenia", usu_UsuarioParameter, usu_ContraseniaParameter);
        }
    
        public virtual ObjectResult<UDP_CargarTablaDirecciones_Result1> UDP_CargarTablaDirecciones(Nullable<int> cli_Id)
        {
            var cli_IdParameter = cli_Id.HasValue ?
                new ObjectParameter("cli_Id", cli_Id) :
                new ObjectParameter("cli_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_CargarTablaDirecciones_Result1>("UDP_CargarTablaDirecciones", cli_IdParameter);
        }
    
        public virtual ObjectResult<UDP_LoginDefinitivo100RealPAPA_Result> UDP_LoginDefinitivo100RealPAPA(string usu_Usuario, string usu_Contrasenia)
        {
            var usu_UsuarioParameter = usu_Usuario != null ?
                new ObjectParameter("usu_Usuario", usu_Usuario) :
                new ObjectParameter("usu_Usuario", typeof(string));
    
            var usu_ContraseniaParameter = usu_Contrasenia != null ?
                new ObjectParameter("usu_Contrasenia", usu_Contrasenia) :
                new ObjectParameter("usu_Contrasenia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_LoginDefinitivo100RealPAPA_Result>("UDP_LoginDefinitivo100RealPAPA", usu_UsuarioParameter, usu_ContraseniaParameter);
        }
    
        public virtual int UDP_PedidoDetalle_Update(Nullable<int> pede_Id, Nullable<int> art_Id, Nullable<int> pede_Cantidad, Nullable<decimal> pede_Precio, Nullable<int> pede_UsuarioModificacion)
        {
            var pede_IdParameter = pede_Id.HasValue ?
                new ObjectParameter("pede_Id", pede_Id) :
                new ObjectParameter("pede_Id", typeof(int));
    
            var art_IdParameter = art_Id.HasValue ?
                new ObjectParameter("art_Id", art_Id) :
                new ObjectParameter("art_Id", typeof(int));
    
            var pede_CantidadParameter = pede_Cantidad.HasValue ?
                new ObjectParameter("pede_Cantidad", pede_Cantidad) :
                new ObjectParameter("pede_Cantidad", typeof(int));
    
            var pede_PrecioParameter = pede_Precio.HasValue ?
                new ObjectParameter("pede_Precio", pede_Precio) :
                new ObjectParameter("pede_Precio", typeof(decimal));
    
            var pede_UsuarioModificacionParameter = pede_UsuarioModificacion.HasValue ?
                new ObjectParameter("pede_UsuarioModificacion", pede_UsuarioModificacion) :
                new ObjectParameter("pede_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_PedidoDetalle_Update", pede_IdParameter, art_IdParameter, pede_CantidadParameter, pede_PrecioParameter, pede_UsuarioModificacionParameter);
        }
    
        public virtual ObjectResult<UDP_CargarTablaPedidos_Result2> UDP_CargarTablaPedidos(Nullable<int> ped_Id)
        {
            var ped_IdParameter = ped_Id.HasValue ?
                new ObjectParameter("ped_Id", ped_Id) :
                new ObjectParameter("ped_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_CargarTablaPedidos_Result2>("UDP_CargarTablaPedidos", ped_IdParameter);
        }
    
        public virtual int UDP_tbEstadoCivilesInsert(string estciv_Id, string estciv_Nombre, Nullable<int> estciv_UsuarioCreacion)
        {
            var estciv_IdParameter = estciv_Id != null ?
                new ObjectParameter("estciv_Id", estciv_Id) :
                new ObjectParameter("estciv_Id", typeof(string));
    
            var estciv_NombreParameter = estciv_Nombre != null ?
                new ObjectParameter("estciv_Nombre", estciv_Nombre) :
                new ObjectParameter("estciv_Nombre", typeof(string));
    
            var estciv_UsuarioCreacionParameter = estciv_UsuarioCreacion.HasValue ?
                new ObjectParameter("estciv_UsuarioCreacion", estciv_UsuarioCreacion) :
                new ObjectParameter("estciv_UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbEstadoCivilesInsert", estciv_IdParameter, estciv_NombreParameter, estciv_UsuarioCreacionParameter);
        }
    
        public virtual int UDP_tbEstadoCivilesUpdate(string estciv_Id, string estciv_Nombre, Nullable<int> estciv_UsuarioModificacion)
        {
            var estciv_IdParameter = estciv_Id != null ?
                new ObjectParameter("estciv_Id", estciv_Id) :
                new ObjectParameter("estciv_Id", typeof(string));
    
            var estciv_NombreParameter = estciv_Nombre != null ?
                new ObjectParameter("estciv_Nombre", estciv_Nombre) :
                new ObjectParameter("estciv_Nombre", typeof(string));
    
            var estciv_UsuarioModificacionParameter = estciv_UsuarioModificacion.HasValue ?
                new ObjectParameter("estciv_UsuarioModificacion", estciv_UsuarioModificacion) :
                new ObjectParameter("estciv_UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbEstadoCivilesUpdate", estciv_IdParameter, estciv_NombreParameter, estciv_UsuarioModificacionParameter);
        }
    
        public virtual int UDP_tbEstadoCivilesDelete(string estciv_Id)
        {
            var estciv_IdParameter = estciv_Id != null ?
                new ObjectParameter("estciv_Id", estciv_Id) :
                new ObjectParameter("estciv_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDP_tbEstadoCivilesDelete", estciv_IdParameter);
        }
    
        public virtual ObjectResult<UDP_CargarTodoMunicipio_Result1> UDP_CargarTodoMunicipio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_CargarTodoMunicipio_Result1>("UDP_CargarTodoMunicipio");
        }
    
        public virtual ObjectResult<UDP_cargarMunicipioDeEmpleados_Result> UDP_cargarMunicipioDeEmpleados(Nullable<int> emp_Id)
        {
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_cargarMunicipioDeEmpleados_Result>("UDP_cargarMunicipioDeEmpleados", emp_IdParameter);
        }
    
        public virtual ObjectResult<UDP_cargarMunicipioDeDirecciones_Result> UDP_cargarMunicipioDeDirecciones(Nullable<int> dire_Id)
        {
            var dire_IdParameter = dire_Id.HasValue ?
                new ObjectParameter("dire_Id", dire_Id) :
                new ObjectParameter("dire_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_cargarMunicipioDeDirecciones_Result>("UDP_cargarMunicipioDeDirecciones", dire_IdParameter);
        }
    }
}
