
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbCategoria
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbCategoria()
    {

        this.tbArticulos = new HashSet<tbArticulos>();

    }


    public int cat_Id { get; set; }

    public string cat_Descripcion { get; set; }

    public System.DateTime cat_FechaCreacion { get; set; }

    public int cat_UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> cat_FechaModificacion { get; set; }

    public Nullable<int> cat_UsuarioModificacion { get; set; }

    public bool cat_Estado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbArticulos> tbArticulos { get; set; }

    public virtual tbUsuarios tbUsuarios { get; set; }

    public virtual tbUsuarios tbUsuarios1 { get; set; }

}

}
