//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDepartamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDepartamentos()
        {
            this.tbMunicipios = new HashSet<tbMunicipios>();
        }
    
        public string dep_Id { get; set; }
        public string dep_Nombre { get; set; }
        public System.DateTime dep_FechaCreacion { get; set; }
        public int dep_UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> dep_FechaModificacion { get; set; }
        public Nullable<int> dep_UsuarioModificacion { get; set; }
        public bool dep_Estado { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMunicipios> tbMunicipios { get; set; }
    }
}
