//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFabricas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbFabricas()
        {
            this.tbArticulos = new HashSet<tbArticulos>();
        }
    
        public int fab_id { get; set; }
        public string fab_Nombre { get; set; }
        public string mun_Id { get; set; }
        public string fab_DireccionExacta { get; set; }
        public string fab_Telefono { get; set; }
        public System.DateTime fab_FechaCreacion { get; set; }
        public int fab_UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> fab_FechaModificacion { get; set; }
        public Nullable<int> fab_UsuarioModificacion { get; set; }
        public bool fab_Estado { get; set; }
    
        public virtual tbMunicipios tbMunicipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbArticulos> tbArticulos { get; set; }
    }
}
