
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbMetodoPago
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbMetodoPago()
    {

        this.tbPedidos = new HashSet<tbPedidos>();

    }


    public string metpago_Id { get; set; }

    public string metpago_Descripcion { get; set; }

    public System.DateTime metpago_FechaCreacion { get; set; }

    public int metpago_UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> metpago_FechaModificacion { get; set; }

    public Nullable<int> metpago_UsuarioModificacion { get; set; }

    public bool metpago_Estado { get; set; }



    public virtual tbUsuarios tbUsuarios { get; set; }

    public virtual tbUsuarios tbUsuarios1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbPedidos> tbPedidos { get; set; }

}

}
