
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbPedidos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbPedidos()
    {

        this.tbPedidosDetalles = new HashSet<tbPedidosDetalles>();

    }


    public int ped_Id { get; set; }

    public int cli_Id { get; set; }

    public System.DateTime ped_Fecha { get; set; }

    public Nullable<int> dire_id { get; set; }

    public int emp_id { get; set; }

    public string metpago_Id { get; set; }

    public System.DateTime ped_FechaCreacion { get; set; }

    public int ped_UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> ped_FechaModificacion { get; set; }

    public Nullable<int> ped_UsuarioModificacion { get; set; }

    public bool ped_Estado { get; set; }



    public virtual tbClientes tbClientes { get; set; }

    public virtual tbDirecciones tbDirecciones { get; set; }

    public virtual tbEmpleados tbEmpleados { get; set; }

    public virtual tbMetodoPago tbMetodoPago { get; set; }

    public virtual tbUsuarios tbUsuarios { get; set; }

    public virtual tbUsuarios tbUsuarios1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbPedidosDetalles> tbPedidosDetalles { get; set; }

}

}
