//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRolesXPantalla
    {
        public int ropa_id { get; set; }
        public Nullable<int> rol_id { get; set; }
        public Nullable<int> pan_id { get; set; }
        public int ropa_UsuarioCreacion { get; set; }
        public System.DateTime ropa_FechaCreacion { get; set; }
        public Nullable<int> ropa_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> ropa_FechaModificacion { get; set; }
        public bool ropa_Estado { get; set; }
    
        public virtual tbPantallas tbPantallas { get; set; }
        public virtual tbRoles tbRoles { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
