
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbRoles
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbRoles()
    {

        this.tbUsuarios2 = new HashSet<tbUsuarios>();

        this.tbRolesXPantalla = new HashSet<tbRolesXPantalla>();

    }


    public int rol_id { get; set; }

    public string rol_Nombre { get; set; }

    public int rol_UsuarioCreacion { get; set; }

    public System.DateTime rol_FechaCreacion { get; set; }

    public Nullable<int> rol_UsuarioModificacion { get; set; }

    public Nullable<System.DateTime> rol_FechaModificacion { get; set; }

    public bool rol_Estado { get; set; }



    public virtual tbUsuarios tbUsuarios { get; set; }

    public virtual tbUsuarios tbUsuarios1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbUsuarios> tbUsuarios2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbRolesXPantalla> tbRolesXPantalla { get; set; }

}

}
