//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC.Models
{
    using System;
    
    public partial class UDP_CargarTodoMunicipio_Result1
    {
        public string mun_Id { get; set; }
        public string mun_Nombre { get; set; }
        public string dep_Id { get; set; }
        public string dep_Nombre { get; set; }
        public System.DateTime mun_FechaCreacion { get; set; }
        public int mun_UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> mun_FechaModificacion { get; set; }
        public Nullable<int> mun_UsuarioModificacion { get; set; }
        public bool mun_Estado { get; set; }
    }
}
